name: Deploy to Server with Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted # This targets your self-hosted runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Pull and Restart
      run: |
        cd /home/marto/shutupandtakemythings # The path to your project on the server
        git pull origin main
        pm2 restart item-store
  notify:
    runs-on: ubuntu-latest
    needs: deploy 
    if: always() 
    steps:
    - name: Send Discord notification
      uses: rjtmahy/discord-webhook-notification@v1
      with:
        webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        # The 'needs' context gives us the result of the 'deploy' job
        title: "Deployment to shutupandtakemythings"
        description: "Job status: ${{ needs.deploy.result }}"
        # Set the color based on success or failure
        color: ${{ needs.deploy.result == 'success' && '32768' || '16711680' }} # Green for success, Red for failure
        fields: |
          [
            {"name": "Repository", "value": "${{ github.repository }}", "inline": true},
            {"name": "Triggered by", "value": "${{ github.actor }}", "inline": true},
            {"name": "Commit", "value": "[${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})"}
          ]
    
    - name: Send ntfy notification on success
      if: needs.deploy.result == 'success'
      run: |
        curl -X POST \
        -H "Title: ✅ Deployment Successful" \
        -H "Tags: white_check_mark,rocket" \
        -d "Successfully deployed to ${{ github.repository }}" \
        ${{ secrets.NTFY_TOPIC_URL }}

    - name: Send ntfy notification on failure
      if: needs.deploy.result == 'failure'
      run: |
        curl -X POST \
        -H "Title: ❌ Deployment Failed" \
        -H "Prio: high" \
        -H "Tags: x,warning" \
        -d "Failed to deploy ${{ github.repository }}. Commit by ${{ github.actor }}. See details here: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
        ${{ secrets.NTFY_TOPIC_URL }}
        
    